# Generated by Django 4.2.23 on 2026-02-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=120)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='продолжительность этого сеанаса вминутах')),
                ('required_score_pass', models.IntegerField(help_text='бал в процентах %')),
                ('difficluty', models.CharField(choices=[('легкий', 'легкий'), ('средний', 'среданий'), ('сложный', 'сложный')], max_length=10)),
            ],
        ),
    ]
